# Generated by Django 4.2.11 on 2026-05-26 15:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('VIEWER', 'Viewer')], default='ANALYST', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_json', models.JSONField()),
                ('source_row_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.ingestionbatch')),
            ],
            options={
                'ordering': ['source_row_number'],
            },
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 – Direct'), (2, 'Scope 2 – Electricity'), (3, 'Scope 3 – Value Chain')])),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('PROCUREMENT', 'Procurement'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel Stay'), ('GROUND', 'Ground Transport')], max_length=20)),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(choices=[('L', 'Litres'), ('GAL', 'Gallons'), ('KG', 'Kilograms'), ('KWH', 'Kilowatt-hours'), ('MWH', 'Megawatt-hours'), ('KM', 'Kilometres'), ('MI', 'Miles'), ('NIGHTS', 'Nights'), ('OTHER', 'Other')], max_length=10)),
                ('activity_unit_normalized', models.DecimalField(decimal_places=4, help_text='Always in SI base unit (L, kWh, km)', max_digits=18)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='kg CO2 equivalent — null if emission factor not available', max_digits=18, null=True)),
                ('emission_factor_used', models.CharField(blank=True, max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('origin_iata', models.CharField(blank=True, max_length=10)),
                ('destination_iata', models.CharField(blank=True, max_length=10)),
                ('travel_class', models.CharField(blank=True, max_length=50)),
                ('meter_id', models.CharField(blank=True, max_length=100)),
                ('tariff_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged – Needs Attention')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True after audit export — no further edits allowed')),
                ('source_amended', models.BooleanField(default=False, help_text='True if this record was manually edited after ingestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.ingestionbatch')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_record', to='core.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('EDITED', 'Edited'), ('LOCKED', 'Locked for Audit')], max_length=20)),
                ('old_value_json', models.JSONField(blank=True, null=True)),
                ('new_value_json', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.emissionrecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werks_code', models.CharField(max_length=10)),
                ('plant_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_lookups', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'werks_code')},
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='core_emissi_tenant__581034_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='core_emissi_tenant__fc19e0_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='core_emissi_batch_i_0918bd_idx'),
        ),
    ]
